// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Gateway.DataLayer.SqlServer;

namespace O10.Gateway.DataLayer.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerDataContext))]
    [Migration("20210619013227_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("AddressId");

                    b.HasIndex("Key");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.AssociatedAttributeIssuance", b =>
                {
                    b.Property<long>("AssociatedAttributeIssuanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("IssuanceCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<long>("IssuerAddressId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RootIssuanceCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("AssociatedAttributeIssuanceId");

                    b.HasIndex("IssuanceCommitment");

                    b.HasIndex("IssuerAddressId");

                    b.HasIndex("RootIssuanceCommitment");

                    b.ToTable("AssociatedAttributeIssuances");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.CompromisedKeyImage", b =>
                {
                    b.Property<long>("CompromisedKeyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("KeyImage")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("CompromisedKeyImageId");

                    b.HasIndex("KeyImage")
                        .IsUnique();

                    b.ToTable("CompromisedKeyImages");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.KeyImage", b =>
                {
                    b.Property<long>("KeyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("KeyImageId");

                    b.HasIndex("Value");

                    b.ToTable("UtxoKeyImages");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RegistryCombinedBlock", b =>
                {
                    b.Property<long>("RegistryCombinedBlockId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegistryCombinedBlockId");

                    b.ToTable("RegistryCombinedBlocks");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RegistryFullBlockData", b =>
                {
                    b.Property<long>("RegistryFullBlockDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CombinedBlockHeight")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("RegistryFullBlockDataId");

                    b.HasIndex("CombinedBlockHeight");

                    b.ToTable("RegistryFullBlocks");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RelationRecord", b =>
                {
                    b.Property<long>("RelationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("GroupCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Issuer")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("RegistrationCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("RelationRecordId");

                    b.HasIndex("IsRevoked");

                    b.HasIndex("Issuer");

                    b.HasIndex("RegistrationCommitment");

                    b.ToTable("RelationRecords");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RootAttribute", b =>
                {
                    b.Property<long>("RootAttributeIssuanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsOverriden")
                        .HasColumnType("bit");

                    b.Property<long>("IssuanceCombinedBlock")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("IssuanceCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<long>("IssuerAddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("RevocationCombinedBlock")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RootCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("RootAttributeIssuanceId");

                    b.HasIndex("IsOverriden");

                    b.HasIndex("IssuanceCommitment");

                    b.HasIndex("IssuerAddressId");

                    b.HasIndex("RootCommitment");

                    b.ToTable("RootAttributes");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StateTransaction", b =>
                {
                    b.Property<long>("StateTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("HashTransactionHashId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OutputStealthOutputId")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceAddressId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TargetAddressId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TransactionKeyId")
                        .HasColumnType("bigint");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<long>("WitnessId")
                        .HasColumnType("bigint");

                    b.HasKey("StateTransactionId");

                    b.HasIndex("HashTransactionHashId");

                    b.HasIndex("OutputStealthOutputId");

                    b.HasIndex("SourceAddressId");

                    b.HasIndex("TargetAddressId");

                    b.HasIndex("TransactionKeyId");

                    b.HasIndex("WitnessId");

                    b.ToTable("StateTransactions");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StealthOutput", b =>
                {
                    b.Property<long>("StealthOutputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Commitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("DestinationKey")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<bool>("IsOverriden")
                        .HasColumnType("bit");

                    b.Property<byte[]>("OriginatingCommitment")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("StealthOutputId");

                    b.HasIndex("Commitment");

                    b.HasIndex("DestinationKey");

                    b.HasIndex("IsOverriden");

                    b.ToTable("StealthOutputs");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StealthTransaction", b =>
                {
                    b.Property<long>("StealthTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HashTransactionHashId")
                        .HasColumnType("bigint");

                    b.Property<long>("KeyImageId")
                        .HasColumnType("bigint");

                    b.Property<long>("OutputStealthOutputId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransactionKeyId")
                        .HasColumnType("bigint");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<long>("WitnessId")
                        .HasColumnType("bigint");

                    b.HasKey("StealthTransactionId");

                    b.HasIndex("HashTransactionHashId");

                    b.HasIndex("KeyImageId");

                    b.HasIndex("OutputStealthOutputId");

                    b.HasIndex("TransactionKeyId");

                    b.HasIndex("WitnessId");

                    b.ToTable("StealthTransactions");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.SyncBlock", b =>
                {
                    b.Property<long>("SyncBlockId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("SyncBlockId");

                    b.ToTable("SyncBlocks");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.TransactionHash", b =>
                {
                    b.Property<long>("TransactionHashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AggregatedTransactionsHeight")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("TransactionHashId");

                    b.HasIndex("AggregatedTransactionsHeight", "Hash");

                    b.ToTable("TransactionHashes");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.TransactionKey", b =>
                {
                    b.Property<long>("TransactionKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("TransactionKeyId");

                    b.HasIndex("Key");

                    b.ToTable("TransactionKeys");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.WitnessPacket", b =>
                {
                    b.Property<long>("WitnessPacketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CombinedBlockHeight")
                        .HasColumnType("bigint");

                    b.Property<long>("ReferencedBodyHashTransactionHashId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ReferencedDestinationKey")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("ReferencedDestinationKey2")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("ReferencedKeyImage")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<int>("ReferencedLedgerType")
                        .HasColumnType("int");

                    b.Property<int>("ReferencedPacketType")
                        .HasColumnType("int");

                    b.Property<byte[]>("ReferencedTransactionKey")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<long>("Round")
                        .HasColumnType("bigint");

                    b.Property<long>("SyncBlockHeight")
                        .HasColumnType("bigint");

                    b.HasKey("WitnessPacketId");

                    b.HasIndex("CombinedBlockHeight");

                    b.HasIndex("ReferencedBodyHashTransactionHashId");

                    b.HasIndex("ReferencedDestinationKey");

                    b.HasIndex("ReferencedDestinationKey2");

                    b.HasIndex("ReferencedKeyImage");

                    b.HasIndex("ReferencedTransactionKey");

                    b.ToTable("WitnessPackets");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.AssociatedAttributeIssuance", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssuerAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RootAttribute", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssuerAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StateTransaction", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.TransactionHash", "Hash")
                        .WithMany()
                        .HasForeignKey("HashTransactionHashId");

                    b.HasOne("O10.Gateway.DataLayer.Model.StealthOutput", "Output")
                        .WithMany()
                        .HasForeignKey("OutputStealthOutputId");

                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Source")
                        .WithMany()
                        .HasForeignKey("SourceAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Target")
                        .WithMany()
                        .HasForeignKey("TargetAddressId");

                    b.HasOne("O10.Gateway.DataLayer.Model.TransactionKey", "TransactionKey")
                        .WithMany()
                        .HasForeignKey("TransactionKeyId");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StealthTransaction", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.TransactionHash", "Hash")
                        .WithMany()
                        .HasForeignKey("HashTransactionHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O10.Gateway.DataLayer.Model.KeyImage", "KeyImage")
                        .WithMany()
                        .HasForeignKey("KeyImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O10.Gateway.DataLayer.Model.StealthOutput", "Output")
                        .WithMany()
                        .HasForeignKey("OutputStealthOutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O10.Gateway.DataLayer.Model.TransactionKey", "TransactionKey")
                        .WithMany()
                        .HasForeignKey("TransactionKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.WitnessPacket", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.TransactionHash", "ReferencedBodyHash")
                        .WithMany()
                        .HasForeignKey("ReferencedBodyHashTransactionHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
