// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Gateway.DataLayer.SqlServer;

namespace O10.Gateway.DataLayer.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerDataContext))]
    partial class SqlServerDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Key")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("AddressId");

                    b.HasIndex("Key");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.AssociatedAttributeIssuance", b =>
                {
                    b.Property<long>("AssociatedAttributeIssuanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("IssuanceCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<long?>("IssuerAddressId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RootIssuanceCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("AssociatedAttributeIssuanceId");

                    b.HasIndex("IssuanceCommitment");

                    b.HasIndex("IssuerAddressId");

                    b.HasIndex("RootIssuanceCommitment");

                    b.ToTable("AssociatedAttributeIssuances");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.CompromisedKeyImage", b =>
                {
                    b.Property<long>("CompromisedKeyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("KeyImage")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("CompromisedKeyImageId");

                    b.HasIndex("KeyImage")
                        .IsUnique()
                        .HasFilter("[KeyImage] IS NOT NULL");

                    b.ToTable("CompromisedKeyImages");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.PacketHash", b =>
                {
                    b.Property<long>("PacketHashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CombinedRegistryBlockHeight")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Hash")
                        .HasColumnType("varbinary(64)");

                    b.Property<long>("SyncBlockHeight")
                        .HasColumnType("bigint");

                    b.HasKey("PacketHashId");

                    b.HasIndex("SyncBlockHeight", "CombinedRegistryBlockHeight", "Hash");

                    b.ToTable("PacketHashes");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RegistryCombinedBlock", b =>
                {
                    b.Property<long>("RegistryCombinedBlockId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("RegistryCombinedBlockId");

                    b.ToTable("RegistryCombinedBlocks");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RegistryFullBlockData", b =>
                {
                    b.Property<long>("RegistryFullBlockDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CombinedBlockHeight")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("RegistryFullBlockDataId");

                    b.HasIndex("CombinedBlockHeight");

                    b.ToTable("RegistryFullBlocks");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RelationRecord", b =>
                {
                    b.Property<long>("RelationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("GroupCommitment")
                        .HasColumnType("varbinary(64)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Issuer")
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("RegistrationCommitment")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("RelationRecordId");

                    b.HasIndex("IsRevoked");

                    b.HasIndex("Issuer");

                    b.HasIndex("RegistrationCommitment");

                    b.ToTable("RelationRecords");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RootAttribute", b =>
                {
                    b.Property<long>("RootAttributeIssuanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsOverriden")
                        .HasColumnType("bit");

                    b.Property<long>("IssuanceCombinedBlock")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("IssuanceCommitment")
                        .HasColumnType("varbinary(64)");

                    b.Property<long?>("IssuerAddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("RevocationCombinedBlock")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RootCommitment")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("RootAttributeIssuanceId");

                    b.HasIndex("IsOverriden");

                    b.HasIndex("IssuanceCommitment");

                    b.HasIndex("IssuerAddressId");

                    b.HasIndex("RootCommitment");

                    b.ToTable("RootAttributes");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StealthPacket", b =>
                {
                    b.Property<long>("StealthPacketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlockType")
                        .HasColumnType("int");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<long?>("KeyImageUtxoKeyImageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OutputUtxoOutputId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ThisBlockHashPacketHashId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TransactionKeyUtxoTransactionKeyId")
                        .HasColumnType("bigint");

                    b.Property<long>("WitnessId")
                        .HasColumnType("bigint");

                    b.HasKey("StealthPacketId");

                    b.HasIndex("KeyImageUtxoKeyImageId");

                    b.HasIndex("OutputUtxoOutputId");

                    b.HasIndex("ThisBlockHashPacketHashId");

                    b.HasIndex("TransactionKeyUtxoTransactionKeyId");

                    b.HasIndex("WitnessId");

                    b.ToTable("StealthPackets");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.SyncBlock", b =>
                {
                    b.Property<long>("SyncBlockId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Hash")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("SyncBlockId");

                    b.ToTable("SyncBlocks");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.TransactionalPacket", b =>
                {
                    b.Property<long>("TransactionalPacketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlockType")
                        .HasColumnType("int");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("GroupId")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("Height")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsTransition")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<long?>("OutputUtxoOutputId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceAddressId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TargetAddressId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ThisBlockHashPacketHashId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TransactionKeyUtxoTransactionKeyId")
                        .HasColumnType("bigint");

                    b.Property<long>("WitnessId")
                        .HasColumnType("bigint");

                    b.HasKey("TransactionalPacketId");

                    b.HasIndex("OutputUtxoOutputId");

                    b.HasIndex("SourceAddressId");

                    b.HasIndex("TargetAddressId");

                    b.HasIndex("ThisBlockHashPacketHashId");

                    b.HasIndex("TransactionKeyUtxoTransactionKeyId");

                    b.HasIndex("WitnessId");

                    b.ToTable("TransactionalPackets");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.UtxoKeyImage", b =>
                {
                    b.Property<long>("UtxoKeyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("KeyImage")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("UtxoKeyImageId");

                    b.HasIndex("KeyImage");

                    b.ToTable("UtxoKeyImages");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.UtxoOutput", b =>
                {
                    b.Property<long>("UtxoOutputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Commitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("DestinationKey")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<bool>("IsOverriden")
                        .HasColumnType("bit");

                    b.Property<byte[]>("OriginatingCommitment")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("UtxoOutputId");

                    b.HasIndex("Commitment");

                    b.HasIndex("DestinationKey");

                    b.HasIndex("IsOverriden");

                    b.ToTable("UtxoOutputs");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.UtxoTransactionKey", b =>
                {
                    b.Property<long>("UtxoTransactionKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Key")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("UtxoTransactionKeyId");

                    b.HasIndex("Key");

                    b.ToTable("UtxoTransactionKeys");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.WitnessPacket", b =>
                {
                    b.Property<long>("WitnessPacketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CombinedBlockHeight")
                        .HasColumnType("bigint");

                    b.Property<int>("ReferencedBlockType")
                        .HasColumnType("int");

                    b.Property<long?>("ReferencedBodyHashPacketHashId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ReferencedDestinationKey")
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("ReferencedDestinationKey2")
                        .HasColumnType("varbinary(64)");

                    b.Property<byte[]>("ReferencedKeyImage")
                        .HasColumnType("varbinary(64)");

                    b.Property<int>("ReferencedPacketType")
                        .HasColumnType("int");

                    b.Property<byte[]>("ReferencedTransactionKey")
                        .HasColumnType("varbinary(64)");

                    b.Property<long>("Round")
                        .HasColumnType("bigint");

                    b.Property<long>("SyncBlockHeight")
                        .HasColumnType("bigint");

                    b.HasKey("WitnessPacketId");

                    b.HasIndex("CombinedBlockHeight");

                    b.HasIndex("ReferencedBodyHashPacketHashId");

                    b.HasIndex("ReferencedDestinationKey");

                    b.HasIndex("ReferencedDestinationKey2");

                    b.HasIndex("ReferencedKeyImage");

                    b.HasIndex("ReferencedTransactionKey");

                    b.ToTable("WitnessPackets");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.AssociatedAttributeIssuance", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssuerAddressId");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RootAttribute", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssuerAddressId");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StealthPacket", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.UtxoKeyImage", "KeyImage")
                        .WithMany()
                        .HasForeignKey("KeyImageUtxoKeyImageId");

                    b.HasOne("O10.Gateway.DataLayer.Model.UtxoOutput", "Output")
                        .WithMany()
                        .HasForeignKey("OutputUtxoOutputId");

                    b.HasOne("O10.Gateway.DataLayer.Model.PacketHash", "ThisBlockHash")
                        .WithMany()
                        .HasForeignKey("ThisBlockHashPacketHashId");

                    b.HasOne("O10.Gateway.DataLayer.Model.UtxoTransactionKey", "TransactionKey")
                        .WithMany()
                        .HasForeignKey("TransactionKeyUtxoTransactionKeyId");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.TransactionalPacket", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.UtxoOutput", "Output")
                        .WithMany()
                        .HasForeignKey("OutputUtxoOutputId");

                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Source")
                        .WithMany()
                        .HasForeignKey("SourceAddressId");

                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Target")
                        .WithMany()
                        .HasForeignKey("TargetAddressId");

                    b.HasOne("O10.Gateway.DataLayer.Model.PacketHash", "ThisBlockHash")
                        .WithMany()
                        .HasForeignKey("ThisBlockHashPacketHashId");

                    b.HasOne("O10.Gateway.DataLayer.Model.UtxoTransactionKey", "TransactionKey")
                        .WithMany()
                        .HasForeignKey("TransactionKeyUtxoTransactionKeyId");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.WitnessPacket", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.PacketHash", "ReferencedBodyHash")
                        .WithMany()
                        .HasForeignKey("ReferencedBodyHashPacketHashId");
                });
#pragma warning restore 612, 618
        }
    }
}
