// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Node.DataLayer.Specific.Stealth.DataContexts.SqlServer;

namespace O10.Node.DataLayer.Specific.Stealth.DataContexts.SqlServer
{
    [DbContext(typeof(DataContext))]
    [Migration("20210123032229_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Stealth.Model.KeyImage", b =>
                {
                    b.Property<long>("KeyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Value")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("KeyImageId");

                    b.HasIndex("Value");

                    b.ToTable("KeyImages");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Stealth.Model.StealthTransaction", b =>
                {
                    b.Property<long>("StealthTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlockType")
                        .HasColumnType("int");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("DestinationKey")
                        .HasColumnType("varbinary(64)");

                    b.Property<long?>("HashKeyStealthTransactionHashKeyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("KeyImageId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SyncBlockHeight")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("StealthTransactionId");

                    b.HasIndex("HashKeyStealthTransactionHashKeyId");

                    b.HasIndex("KeyImageId");

                    b.HasIndex("SyncBlockHeight");

                    b.ToTable("StealthTransactions");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Stealth.Model.StealthTransactionHashKey", b =>
                {
                    b.Property<long>("StealthTransactionHashKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CombinedBlockHeight")
                        .HasColumnType("decimal(20,0)");

                    b.Property<byte[]>("Hash")
                        .HasColumnType("varbinary(64)");

                    b.Property<decimal>("SyncBlockHeight")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("StealthTransactionHashKeyId");

                    b.HasIndex("Hash");

                    b.HasIndex("SyncBlockHeight");

                    b.ToTable("StealthTransactionHashKeys");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Stealth.Model.StealthTransaction", b =>
                {
                    b.HasOne("O10.Node.DataLayer.Specific.Stealth.Model.StealthTransactionHashKey", "HashKey")
                        .WithMany()
                        .HasForeignKey("HashKeyStealthTransactionHashKeyId");

                    b.HasOne("O10.Node.DataLayer.Specific.Stealth.Model.KeyImage", "KeyImage")
                        .WithMany()
                        .HasForeignKey("KeyImageId");
                });
#pragma warning restore 612, 618
        }
    }
}
