// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Client.DataLayer.SQLite;

namespace O10.Client.DataLayer.SQLite.Migrations
{
    [DbContext(typeof(SQLiteDataContext))]
    partial class SQLiteDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("O10.Client.DataLayer.ElectionCommittee.EcCandidateRecord", b =>
                {
                    b.Property<long>("EcCandidateRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EcPollRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EcCandidateRecordId");

                    b.HasIndex("EcPollRecordId");

                    b.HasIndex("Name");

                    b.ToTable("EcCandidateRecords");
                });

            modelBuilder.Entity("O10.Client.DataLayer.ElectionCommittee.EcPollRecord", b =>
                {
                    b.Property<long>("EcPollRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("EcPollRecordId");

                    b.HasIndex("Name");

                    b.ToTable("EcPollRecords");
                });

            modelBuilder.Entity("O10.Client.DataLayer.ElectionCommittee.EcPollSelection", b =>
                {
                    b.Property<long>("EcPollSelectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EcBlindingFactor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EcCommitment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EcPollRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoterBlindingFactor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EcPollSelectionId");

                    b.HasIndex("EcCommitment");

                    b.HasIndex("EcPollRecordId");

                    b.ToTable("EcPollSelections");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.Account", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompromised")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastAggregatedRegistrations")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicSpendKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PublicViewKey")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SecretSpendKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SecretViewKey")
                        .HasColumnType("BLOB");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.AccountKeyValue", b =>
                {
                    b.Property<long>("AccountKeyValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountKeyValueId");

                    b.HasIndex("AccountId");

                    b.HasIndex("Key");

                    b.ToTable("AccountKeyValues");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.AssociatedAttributeBackup", b =>
                {
                    b.Property<long>("AssociatedAttributeBackupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssociatedIssuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootAssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootIssuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssociatedAttributeBackupId");

                    b.HasIndex("RootAssetId");

                    b.HasIndex("RootIssuer");

                    b.ToTable("AssociatedAttributeBackups");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.AutoLogin", b =>
                {
                    b.Property<long>("AutoLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SecretKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("AutoLoginId");

                    b.HasIndex("AccountId");

                    b.ToTable("AutoLogins");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.BiometricRecord", b =>
                {
                    b.Property<long>("BiometricRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BiometricRecordId");

                    b.HasIndex("UserData")
                        .IsUnique();

                    b.ToTable("BiometricRecords");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.ConsentManagement.ConsentManagementSettings", b =>
                {
                    b.Property<long>("ConsentManagementSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsentManagementSettingsId");

                    b.ToTable("ConsentManagementSettings");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.ExternalIdentityProvider", b =>
                {
                    b.Property<long>("ExternalIdentityProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ExternalIdentityProviderId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExternalIdentityProviders");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.IdentitiesScheme", b =>
                {
                    b.Property<long>("IdentitiesSchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributeSchemeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanBeRoot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdentitiesSchemeId");

                    b.HasIndex("AttributeName");

                    b.HasIndex("Issuer");

                    b.ToTable("IdentitiesSchemes");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.Identity", b =>
                {
                    b.Property<long>("IdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdentityId");

                    b.ToTable("Identities");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.IdentityAttribute", b =>
                {
                    b.Property<long>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Commitment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("IdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subject")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttributeId");

                    b.HasIndex("Commitment");

                    b.HasIndex("IdentityId");

                    b.ToTable("IdentityAttributes");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.IdentityTarget", b =>
                {
                    b.Property<long>("IdentityTargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("IdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicSpendKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicViewKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdentityTargetId");

                    b.HasIndex("IdentityId");

                    b.ToTable("IdentityTargets");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.Inherence.InherenceSetting", b =>
                {
                    b.Property<long>("InherenceSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InherenceSettingId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InherenceSettings");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.ProcessedWitness", b =>
                {
                    b.Property<long>("ProcessedWitnessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<long>("WitnessId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProcessedWitnessId");

                    b.HasIndex("AccountId", "WitnessId")
                        .IsUnique();

                    b.ToTable("ProcessedWitnesss");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SamlIdentityProvider", b =>
                {
                    b.Property<long>("SamlIdentityProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicSpendKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretViewKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SamlIdentityProviderId");

                    b.HasIndex("EntityId");

                    b.ToTable("SamlIdentityProviders");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SamlServiceProvider", b =>
                {
                    b.Property<long>("SamlServiceProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SingleLogoutUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SamlServiceProviderId");

                    b.HasIndex("EntityId");

                    b.ToTable("SamlServiceProviders");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SamlSettings", b =>
                {
                    b.Property<long>("SamlSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DefaultSamlIdpAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DefaultSamlIdpId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SamlSettingsId");

                    b.ToTable("SamlSettings");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.Scenarios.ScenarioAccount", b =>
                {
                    b.Property<long>("ScenarioAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScenarioSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScenarioAccountId");

                    b.HasIndex("ScenarioSessionId");

                    b.ToTable("ScenarioAccounts");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.Scenarios.ScenarioSession", b =>
                {
                    b.Property<long>("ScenarioSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScenarioSessionId");

                    b.HasIndex("UserSubject");

                    b.ToTable("ScenarioSessions");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.ServiceProviderRegistration", b =>
                {
                    b.Property<long>("ServiceProviderRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Commitment")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ServiceProviderRegistrationId");

                    b.ToTable("ServiceProviderRegistrations");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.ServiceProviders.GroupRelation", b =>
                {
                    b.Property<long>("GroupRelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupOwnerKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GroupRelationId");

                    b.HasIndex("AssetId");

                    b.HasIndex("Issuer");

                    b.ToTable("GroupRelations");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.ServiceProviders.RegistrationCommitment", b =>
                {
                    b.Property<long>("RegistrationCommitmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Commitment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceProviderInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RegistrationCommitmentId");

                    b.HasIndex("AssetId");

                    b.HasIndex("Commitment")
                        .IsUnique();

                    b.HasIndex("Issuer");

                    b.ToTable("RegistrationCommitments");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.ServiceProviders.RelationGroup", b =>
                {
                    b.Property<long>("RelationGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RelationGroupId");

                    b.HasIndex("AccountId");

                    b.ToTable("RelationGroups");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.ServiceProviders.RelationRecord", b =>
                {
                    b.Property<long>("RelationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RegistrationCommitmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RelationGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootAttributeValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RelationRecordId");

                    b.HasIndex("AccountId");

                    b.HasIndex("RegistrationCommitmentId");

                    b.HasIndex("RelationGroupId");

                    b.ToTable("RelationRecords");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.ServiceProviders.SpUserTransaction", b =>
                {
                    b.Property<long>("SpUserTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompromised")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ServiceProviderRegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpUserTransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("SpUserTransactions");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SpAttribute", b =>
                {
                    b.Property<long>("SpAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AssetId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("AttributeSchemeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("IssuingCommitment")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("OriginalBlindingFactor")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("OriginalCommitment")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpAttributeId");

                    b.ToTable("SpAttributes");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SpDocument", b =>
                {
                    b.Property<long>("SpDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("LastChangeRecordHeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpDocumentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("DocumentName");

                    b.ToTable("SpDocuments");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SpDocumentAllowedSigner", b =>
                {
                    b.Property<long>("SpDocumentAllowedSignerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlindingFactor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DocumentSpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupCommitment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupIssuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpDocumentAllowedSignerId");

                    b.HasIndex("AccountId");

                    b.HasIndex("DocumentSpDocumentId");

                    b.ToTable("SpDocumentAllowedSigners");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SpDocumentSignature", b =>
                {
                    b.Property<long>("SpDocumentSignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DocumentRecordHeight")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("DocumentSignRecord")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long?>("DocumentSpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SignatureRecordHeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpDocumentSignatureId");

                    b.HasIndex("DocumentRecordHeight");

                    b.HasIndex("DocumentSpDocumentId");

                    b.HasIndex("SignatureRecordHeight");

                    b.ToTable("SpDocumentSignatures");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SpIdenitityValidation", b =>
                {
                    b.Property<long>("SpIdenitityValidationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("GroupIdCriterion")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ushort?>("NumericCriterion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("ValidationType")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpIdenitityValidationId");

                    b.ToTable("SpIdenitityValidations");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SynchronizationStatus", b =>
                {
                    b.Property<long>("SynchronizationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdatedCombinedBlockHeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("SynchronizationStatusId");

                    b.HasIndex("AccountId");

                    b.ToTable("SynchronizationStatuses");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SystemSettings", b =>
                {
                    b.Property<int>("SystemSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("BiometricSecretKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("InitializationVector")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("SystemSettingsId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.UserAssociatedAttribute", b =>
                {
                    b.Property<long>("UserAssociatedAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributeSchemeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RootAssetId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserAssociatedAttributeId");

                    b.ToTable("UserAssociatedAttributes");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.UserGroupRelation", b =>
                {
                    b.Property<long>("UserGroupRelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupOwnerKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupOwnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserGroupRelationId");

                    b.HasIndex("AccountId");

                    b.HasIndex("AssetId");

                    b.HasIndex("Issuer");

                    b.ToTable("UserGroupRelations");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.UserRootAttribute", b =>
                {
                    b.Property<long>("UserAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AnchoringOriginationCommitment")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("AssetId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("ConfirmationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOverriden")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("IssuanceCommitment")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("IssuanceTransactionKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("LastBlindingFactor")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("LastCommitment")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("LastDestinationKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("LastTransactionKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextKeyImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("OriginalBlindingFactor")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserAttributeId");

                    b.ToTable("UserRootAttributes");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.UserSettings", b =>
                {
                    b.Property<long>("UserSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoTheftProtection")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserSettingsId");

                    b.HasIndex("AccountId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.UserTransactionSecret", b =>
                {
                    b.Property<long>("UserTransactionSecretId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserTransactionSecretId");

                    b.HasIndex("AccountId");

                    b.HasIndex("KeyImage");

                    b.ToTable("UserTransactionSecrets");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.Users.UserIdentityIssuer", b =>
                {
                    b.Property<long>("UserIdentityIssuerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("UserIdentityIssuerId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("UserIdentityIssuers");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.Users.UserRegistration", b =>
                {
                    b.Property<long>("UserRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Commitment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceProviderInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserRegistrationId");

                    b.HasIndex("AccountId");

                    b.HasIndex("AssetId");

                    b.HasIndex("Issuer");

                    b.ToTable("UserRegistrations");
                });

            modelBuilder.Entity("O10.Client.DataLayer.ElectionCommittee.EcCandidateRecord", b =>
                {
                    b.HasOne("O10.Client.DataLayer.ElectionCommittee.EcPollRecord", "EcPollRecord")
                        .WithMany("Candidates")
                        .HasForeignKey("EcPollRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("O10.Client.DataLayer.ElectionCommittee.EcPollSelection", b =>
                {
                    b.HasOne("O10.Client.DataLayer.ElectionCommittee.EcPollRecord", "EcPollRecord")
                        .WithMany("PollSelections")
                        .HasForeignKey("EcPollRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.AutoLogin", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.IdentityAttribute", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.Identity", "Identity")
                        .WithMany("Attributes")
                        .HasForeignKey("IdentityId");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.Scenarios.ScenarioAccount", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.Scenarios.ScenarioSession", "ScenarioSession")
                        .WithMany()
                        .HasForeignKey("ScenarioSessionId");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.ServiceProviders.RelationGroup", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.ServiceProviders.RelationRecord", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("O10.Client.DataLayer.Model.ServiceProviders.RegistrationCommitment", "RegistrationCommitment")
                        .WithMany()
                        .HasForeignKey("RegistrationCommitmentId");

                    b.HasOne("O10.Client.DataLayer.Model.ServiceProviders.RelationGroup", "RelationGroup")
                        .WithMany()
                        .HasForeignKey("RelationGroupId");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SpDocument", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SpDocumentAllowedSigner", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("O10.Client.DataLayer.Model.SpDocument", "Document")
                        .WithMany("AllowedSigners")
                        .HasForeignKey("DocumentSpDocumentId");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SpDocumentSignature", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.SpDocument", "Document")
                        .WithMany("DocumentSignatures")
                        .HasForeignKey("DocumentSpDocumentId");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.SynchronizationStatus", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.UserGroupRelation", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.UserSettings", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("O10.Client.DataLayer.Model.Users.UserRegistration", b =>
                {
                    b.HasOne("O10.Client.DataLayer.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
