// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Node.DataLayer.Specific.O10Id.DataContexts.SQLite;

namespace O10.Node.DataLayer.Specific.O10Id.DataContexts.SQLite
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.AccountIdentity", b =>
                {
                    b.Property<long>("AccountIdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("KeyHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicKey")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("AccountIdentityId");

                    b.HasIndex("KeyHash");

                    b.ToTable("O10AccountIdentity");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.O10Transaction", b =>
                {
                    b.Property<long>("O10TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("BlockContent")
                        .HasColumnType("BLOB");

                    b.Property<long>("BlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("BlockType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HashKeyO10TransactionHashKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdentityO10TransactionIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SyncBlockHeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("O10TransactionId");

                    b.HasIndex("BlockHeight");

                    b.HasIndex("HashKeyO10TransactionHashKeyId");

                    b.HasIndex("IdentityO10TransactionIdentityId");

                    b.HasIndex("SyncBlockHeight");

                    b.ToTable("O10Transactions");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.O10TransactionHashKey", b =>
                {
                    b.Property<long>("O10TransactionHashKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CombinedBlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasColumnType("varbinary(64)");

                    b.Property<ulong>("SyncBlockHeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("O10TransactionHashKeyId");

                    b.HasIndex("Hash");

                    b.HasIndex("SyncBlockHeight");

                    b.ToTable("O10TransactionHashKeys");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.O10TransactionIdentity", b =>
                {
                    b.Property<long>("O10TransactionIdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdentityAccountIdentityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("O10TransactionIdentityId");

                    b.HasIndex("IdentityAccountIdentityId");

                    b.ToTable("O10TransactionIdentities");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.O10Transaction", b =>
                {
                    b.HasOne("O10.Node.DataLayer.Specific.O10Id.Model.O10TransactionHashKey", "HashKey")
                        .WithMany()
                        .HasForeignKey("HashKeyO10TransactionHashKeyId");

                    b.HasOne("O10.Node.DataLayer.Specific.O10Id.Model.O10TransactionIdentity", "Identity")
                        .WithMany("Transactions")
                        .HasForeignKey("IdentityO10TransactionIdentityId");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.O10TransactionIdentity", b =>
                {
                    b.HasOne("O10.Node.DataLayer.Specific.O10Id.Model.AccountIdentity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityAccountIdentityId");
                });
#pragma warning restore 612, 618
        }
    }
}
