#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Node/O10.Node.WebApp/O10.Node.WebApp.csproj", "Node/O10.Node.WebApp/"]
COPY ["Node/O10.Node.Core/O10.Node.Core.csproj", "Node/O10.Node.Core/"]
COPY ["Common/O10.Transactions.Core/O10.Transactions.Core.csproj", "Common/O10.Transactions.Core/"]
COPY ["Common/Crypto/O10.Crypto/O10.Crypto.csproj", "Common/Crypto/O10.Crypto/"]
COPY ["Common/Crypto/HashLib/CoreHashLib/CoreHashLib.csproj", "Common/Crypto/HashLib/CoreHashLib/"]
COPY ["Common/Crypto/Chaos.NaCl/Chaos.NaCl.csproj", "Common/Crypto/Chaos.NaCl/"]
COPY ["Common/O10.Core/O10.Core.csproj", "Common/O10.Core/"]
COPY ["Node/O10.Node.Network/O10.Node.Network.csproj", "Node/O10.Node.Network/"]
COPY ["Node/O10.Node.DataLayer/O10.Node.DataLayer.csproj", "Node/O10.Node.DataLayer/"]
COPY ["Node/O10.Node.WebApp.Common/O10.Node.WebApp.Common.csproj", "Node/O10.Node.WebApp.Common/"]
RUN dotnet restore "Node/O10.Node.WebApp/O10.Node.WebApp.csproj"
COPY . .
WORKDIR "/src/Node/O10.Node.WebApp"
RUN dotnet build "O10.Node.WebApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "O10.Node.WebApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "O10.Node.WebApp.dll"]