// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Node.DataLayer.Specific.Synchronization.DataContexts.SqlServer;

namespace O10.Node.DataLayer.Specific.Synchronization.DataContexts.SqlServer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Synchronization.Model.AggregatedRegistrationsTransaction", b =>
                {
                    b.Property<long>("AggregatedRegistrationsTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullBlockHashes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SyncBlockHeight")
                        .HasColumnType("bigint");

                    b.HasKey("AggregatedRegistrationsTransactionId");

                    b.HasIndex("SyncBlockHeight");

                    b.ToTable("AggregatedRegistrationsTransactions");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Synchronization.Model.SynchronizationPacket", b =>
                {
                    b.Property<long>("SynchronizationPacketId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MedianTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceiveTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SynchronizationPacketId");

                    b.ToTable("SynchronizationPackets");
                });
#pragma warning restore 612, 618
        }
    }
}
