// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Node.DataLayer.Specific.Registry.DataContexts.SQLite;

namespace O10.Node.DataLayer.Specific.Registry.DataContexts.SQLite.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16");

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Registry.Model.RegistryFullBlock", b =>
                {
                    b.Property<long>("RegistryFullBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Hash")
                        .HasColumnType("varbinary(64)");

                    b.Property<long>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SyncBlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionsCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistryFullBlockId");

                    b.HasIndex("SyncBlockHeight");

                    b.ToTable("RegistryFullBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
