// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Node.DataLayer.Specific.Registry.DataContexts.SqlServer;

namespace O10.Node.DataLayer.Specific.Registry.DataContexts.SqlServer
{
    [DbContext(typeof(DataContext))]
    [Migration("20210123032155_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Registry.Model.RegistryFullBlock", b =>
                {
                    b.Property<long>("RegistryFullBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Hash")
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("HashString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Round")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("SyncBlockHeight")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("TransactionsCount")
                        .HasColumnType("int");

                    b.HasKey("RegistryFullBlockId");

                    b.HasIndex("SyncBlockHeight");

                    b.ToTable("RegistryFullBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
