// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Gateway.DataLayer.SQLite;

namespace O10.Gateway.DataLayer.SQLite.Migrations
{
    [DbContext(typeof(SQLiteDataContext))]
    partial class SQLiteDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("AddressId");

                    b.HasIndex("Key");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.AssociatedAttributeIssuance", b =>
                {
                    b.Property<long>("AssociatedAttributeIssuanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssuanceCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<long>("IssuerAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootIssuanceCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("AssociatedAttributeIssuanceId");

                    b.HasIndex("IssuanceCommitment");

                    b.HasIndex("IssuerAddressId");

                    b.HasIndex("RootIssuanceCommitment");

                    b.ToTable("AssociatedAttributeIssuances");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.CompromisedKeyImage", b =>
                {
                    b.Property<long>("CompromisedKeyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyImage")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("CompromisedKeyImageId");

                    b.HasIndex("KeyImage")
                        .IsUnique();

                    b.ToTable("CompromisedKeyImages");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.KeyImage", b =>
                {
                    b.Property<long>("KeyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("KeyImageId");

                    b.HasIndex("Value");

                    b.ToTable("UtxoKeyImages");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RegistryCombinedBlock", b =>
                {
                    b.Property<long>("RegistryCombinedBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RegistryCombinedBlockId");

                    b.ToTable("RegistryCombinedBlocks");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RegistryFullBlockData", b =>
                {
                    b.Property<long>("RegistryFullBlockDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CombinedBlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("RegistryFullBlockDataId");

                    b.HasIndex("CombinedBlockHeight");

                    b.ToTable("RegistryFullBlocks");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RelationRecord", b =>
                {
                    b.Property<long>("RelationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("RegistrationCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("RelationRecordId");

                    b.HasIndex("IsRevoked");

                    b.HasIndex("Issuer");

                    b.HasIndex("RegistrationCommitment");

                    b.ToTable("RelationRecords");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RootAttribute", b =>
                {
                    b.Property<long>("RootAttributeIssuanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOverriden")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IssuanceCombinedBlock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssuanceCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<long>("IssuerAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RevocationCombinedBlock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootCommitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("RootAttributeIssuanceId");

                    b.HasIndex("IsOverriden");

                    b.HasIndex("IssuanceCommitment");

                    b.HasIndex("IssuerAddressId");

                    b.HasIndex("RootCommitment");

                    b.ToTable("RootAttributes");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StateTransaction", b =>
                {
                    b.Property<long>("StateTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("HashTransactionHashId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OutputStealthOutputId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TargetAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TransactionKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WitnessId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StateTransactionId");

                    b.HasIndex("HashTransactionHashId");

                    b.HasIndex("OutputStealthOutputId");

                    b.HasIndex("SourceAddressId");

                    b.HasIndex("TargetAddressId");

                    b.HasIndex("TransactionKeyId");

                    b.HasIndex("WitnessId");

                    b.ToTable("StateTransactions");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StealthOutput", b =>
                {
                    b.Property<long>("StealthOutputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commitment")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("DestinationKey")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<bool>("IsOverriden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginatingCommitment")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("StealthOutputId");

                    b.HasIndex("Commitment");

                    b.HasIndex("DestinationKey");

                    b.HasIndex("IsOverriden");

                    b.ToTable("StealthOutputs");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StealthTransaction", b =>
                {
                    b.Property<long>("StealthTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("HashTransactionHashId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KeyImageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OutputStealthOutputId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransactionKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WitnessId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StealthTransactionId");

                    b.HasIndex("HashTransactionHashId");

                    b.HasIndex("KeyImageId");

                    b.HasIndex("OutputStealthOutputId");

                    b.HasIndex("TransactionKeyId");

                    b.HasIndex("WitnessId");

                    b.ToTable("StealthTransactions");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.SyncBlock", b =>
                {
                    b.Property<long>("SyncBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("SyncBlockId");

                    b.ToTable("SyncBlocks");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.TransactionHash", b =>
                {
                    b.Property<long>("TransactionHashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AggregatedTransactionsHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("HashString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionHashId");

                    b.HasIndex("AggregatedTransactionsHeight", "Hash");

                    b.ToTable("TransactionHashes");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.TransactionKey", b =>
                {
                    b.Property<long>("TransactionKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.HasKey("TransactionKeyId");

                    b.HasIndex("Key");

                    b.ToTable("TransactionKeys");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.WitnessPacket", b =>
                {
                    b.Property<long>("WitnessPacketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CombinedBlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReferencedBodyHashTransactionHashId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferencedDestinationKey")
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("ReferencedDestinationKey2")
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("ReferencedKeyImage")
                        .HasColumnType("varbinary(64)");

                    b.Property<ushort>("ReferencedLedgerType")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ReferencedPacketType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferencedTransactionKey")
                        .HasColumnType("varbinary(64)");

                    b.Property<long>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SyncBlockHeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("WitnessPacketId");

                    b.HasIndex("CombinedBlockHeight");

                    b.HasIndex("ReferencedBodyHashTransactionHashId");

                    b.HasIndex("ReferencedDestinationKey");

                    b.HasIndex("ReferencedDestinationKey2");

                    b.HasIndex("ReferencedKeyImage");

                    b.HasIndex("ReferencedTransactionKey");

                    b.ToTable("WitnessPackets");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.AssociatedAttributeIssuance", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssuerAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.RootAttribute", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssuerAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StateTransaction", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.TransactionHash", "Hash")
                        .WithMany()
                        .HasForeignKey("HashTransactionHashId");

                    b.HasOne("O10.Gateway.DataLayer.Model.StealthOutput", "Output")
                        .WithMany()
                        .HasForeignKey("OutputStealthOutputId");

                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Source")
                        .WithMany()
                        .HasForeignKey("SourceAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O10.Gateway.DataLayer.Model.Address", "Target")
                        .WithMany()
                        .HasForeignKey("TargetAddressId");

                    b.HasOne("O10.Gateway.DataLayer.Model.TransactionKey", "TransactionKey")
                        .WithMany()
                        .HasForeignKey("TransactionKeyId");
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.StealthTransaction", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.TransactionHash", "Hash")
                        .WithMany()
                        .HasForeignKey("HashTransactionHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O10.Gateway.DataLayer.Model.KeyImage", "KeyImage")
                        .WithMany()
                        .HasForeignKey("KeyImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O10.Gateway.DataLayer.Model.StealthOutput", "Output")
                        .WithMany()
                        .HasForeignKey("OutputStealthOutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O10.Gateway.DataLayer.Model.TransactionKey", "TransactionKey")
                        .WithMany()
                        .HasForeignKey("TransactionKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("O10.Gateway.DataLayer.Model.WitnessPacket", b =>
                {
                    b.HasOne("O10.Gateway.DataLayer.Model.TransactionHash", "ReferencedBodyHash")
                        .WithMany()
                        .HasForeignKey("ReferencedBodyHashTransactionHashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
