// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Node.Core.DataLayer.DataContexts.SQLite;

namespace O10.Node.Core.DataLayer.DataContexts.SQLite
{
    [DbContext(typeof(DataContext))]
    [Migration("20210123032254_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("O10.Node.Core.DataLayer.DataContexts.Gateway", b =>
                {
                    b.Property<int>("GatewayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUri")
                        .HasColumnType("TEXT");

                    b.HasKey("GatewayId");

                    b.HasIndex("BaseUri")
                        .IsUnique();

                    b.ToTable("gateways");
                });

            modelBuilder.Entity("O10.Node.Core.DataLayer.DataContexts.NodeRecord", b =>
                {
                    b.Property<long>("NodeRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPAddress")
                        .HasColumnType("varbinary(32)");

                    b.Property<byte>("NodeRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicKey")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("NodeRecordId");

                    b.HasIndex("PublicKey", "NodeRole")
                        .IsUnique();

                    b.ToTable("NodeRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
