//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O10.Client.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O10.Client.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with id {0} not found.
        /// </summary>
        internal static string ERR_ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofs of value knowledge and binding have different sizes at Associated Attribute with the scheme {0}.
        /// </summary>
        internal static string ERR_ASSOCIATED_PROOF_MALFORMED {
            get {
                return ResourceManager.GetString("ERR_ASSOCIATED_PROOF_MALFORMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofs of Associated Attribute with the scheme {0} are missing.
        /// </summary>
        internal static string ERR_ASSOCIATED_PROOF_MISSING {
            get {
                return ResourceManager.GetString("ERR_ASSOCIATED_PROOF_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of source commitments of proofs of Associated Attribute with the scheme {0} was not found.
        /// </summary>
        internal static string ERR_ASSOCIATED_PROOF_SOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_ASSOCIATED_PROOF_SOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of binding to Root of the Associated Attribute with the scheme {0} is incorrect.
        /// </summary>
        internal static string ERR_ASSOCIATED_PROOF_TO_BINDING {
            get {
                return ResourceManager.GetString("ERR_ASSOCIATED_PROOF_TO_BINDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of value knowledge of the Associated Attribute with the scheme {0} is incorrect.
        /// </summary>
        internal static string ERR_ASSOCIATED_PROOF_TO_VALUE_KNOWLEDGE {
            get {
                return ResourceManager.GetString("ERR_ASSOCIATED_PROOF_TO_VALUE_KNOWLEDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding key not initialized.
        /// </summary>
        internal static string ERR_BINDING_KEY_NOT_INITIALIZED {
            get {
                return ResourceManager.GetString("ERR_BINDING_KEY_NOT_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment eligibility verification failed.
        /// </summary>
        internal static string ERR_COMMITMENT_ELIGIBILITY_VERIFICATION_FAILED {
            get {
                return ResourceManager.GetString("ERR_COMMITMENT_ELIGIBILITY_VERIFICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdP registration failed, details: {0}.
        /// </summary>
        internal static string ERR_INTEGRATION_IDP_REGISTER_FAILED {
            get {
                return ResourceManager.GetString("ERR_INTEGRATION_IDP_REGISTER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain last Registry Combined Block.
        /// </summary>
        internal static string ERR_LAST_REGISTRY_COMBINED_BLOCK_FAILED {
            get {
                return ResourceManager.GetString("ERR_LAST_REGISTRY_COMBINED_BLOCK_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scheme with name &apos;{0}&apos; defined at the issuer &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_NO_SCHEME_OF_ISSUER {
            get {
                return ResourceManager.GetString("ERR_NO_SCHEME_OF_ISSUER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation proofs were not provided.
        /// </summary>
        internal static string ERR_NO_VALIDATION_PROOFS {
            get {
                return ResourceManager.GetString("ERR_NO_VALIDATION_PROOFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchemeResolverService not initialized properly.
        /// </summary>
        internal static string ERR_SCHEME_RESOLVER_SERVICE_NOT_INITIALIZED {
            get {
                return ResourceManager.GetString("ERR_SCHEME_RESOLVER_SERVICE_NOT_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Proofs were incorrect.
        /// </summary>
        internal static string ERR_SP_AUTHENTICATION_FAILED {
            get {
                return ResourceManager.GetString("ERR_SP_AUTHENTICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of proof failed: {0}.
        /// </summary>
        internal static string ERR_VALIDATION_PROOF_FAILED {
            get {
                return ResourceManager.GetString("ERR_VALIDATION_PROOF_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation proofs were not complete for {0}.
        /// </summary>
        internal static string ERR_VALIDATION_PROOFS_NOT_COMPLETE {
            get {
                return ResourceManager.GetString("ERR_VALIDATION_PROOFS_NOT_COMPLETE", resourceCulture);
            }
        }
    }
}
