// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Node.DataLayer.Specific.Stealth.DataContexts.SQLite;

namespace O10.Node.DataLayer.Specific.Stealth.DataContexts.SQLite.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Stealth.Model.KeyImage", b =>
                {
                    b.Property<long>("KeyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("ValueString")
                        .HasColumnType("TEXT");

                    b.HasKey("KeyImageId");

                    b.HasIndex("Value");

                    b.ToTable("KeyImages");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Stealth.Model.StealthTransaction", b =>
                {
                    b.Property<long>("StealthTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("BlockType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationKey")
                        .HasColumnType("varbinary(64)");

                    b.Property<long?>("HashKeyStealthTransactionHashKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("KeyImageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RegistryHeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("StealthTransactionId");

                    b.HasIndex("HashKeyStealthTransactionHashKeyId");

                    b.HasIndex("KeyImageId");

                    b.HasIndex("RegistryHeight");

                    b.ToTable("StealthTransactions");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Stealth.Model.StealthTransactionHashKey", b =>
                {
                    b.Property<long>("StealthTransactionHashKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("HashString")
                        .HasColumnType("TEXT");

                    b.Property<long>("RegistryHeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("StealthTransactionHashKeyId");

                    b.HasIndex("Hash");

                    b.HasIndex("RegistryHeight");

                    b.ToTable("StealthTransactionHashKeys");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Stealth.Model.StealthTransaction", b =>
                {
                    b.HasOne("O10.Node.DataLayer.Specific.Stealth.Model.StealthTransactionHashKey", "HashKey")
                        .WithMany()
                        .HasForeignKey("HashKeyStealthTransactionHashKeyId");

                    b.HasOne("O10.Node.DataLayer.Specific.Stealth.Model.KeyImage", "KeyImage")
                        .WithMany()
                        .HasForeignKey("KeyImageId");
                });
#pragma warning restore 612, 618
        }
    }
}
