//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O10.Client.Mobile.Base.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O10.Client.Mobile.Base.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string BTN_NO {
            get {
                return ResourceManager.GetString("BTN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BTN_OK {
            get {
                return ResourceManager.GetString("BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string BTN_YES {
            get {
                return ResourceManager.GetString("BTN_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ID....
        /// </summary>
        internal static string CAP_ADD_ATTRIBUTES {
            get {
                return ResourceManager.GetString("CAP_ADD_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give an alias for the account.
        /// </summary>
        internal static string CAP_ALIAS {
            get {
                return ResourceManager.GetString("CAP_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string CAP_ASSOCIATED_ATTRIBUTES {
            get {
                return ResourceManager.GetString("CAP_ASSOCIATED_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated attributes by.
        /// </summary>
        internal static string CAP_ASSOCIATED_ATTRS_BY {
            get {
                return ResourceManager.GetString("CAP_ASSOCIATED_ATTRS_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Id:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_ATTRIBUTEID {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_ATTRIBUTEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance commitment:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_ISSUANCE_COMMITMENT {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_ISSUANCE_COMMITMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance commitment as varbinary:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_ISSUANCE_COMMITMENT_VARBINARY {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_ISSUANCE_COMMITMENT_VARBINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_ISSUER {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_ISSUER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer as varbinary:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_ISSUER_VARBINARY {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_ISSUER_VARBINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last blinding factor:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_LAST_BLINDING_FACTOR {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_LAST_BLINDING_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last commitment:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_LAST_COMMITMENT {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_LAST_COMMITMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last destination key:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_LAST_DESTINATION_KEY {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_LAST_DESTINATION_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last transaction key:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_LAST_TRANSACTION_KEY {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_LAST_TRANSACTION_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next key image:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_NEXT_KEY_IMAGE {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_NEXT_KEY_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next key image as varbinary:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_NEXT_KEY_IMAGE_VARBINARY {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_NEXT_KEY_IMAGE_VARBINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original blinding factor:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_ORIGINAL_BLINDING_FACTOR {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_ORIGINAL_BLINDING_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original commitment:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_ORIGINAL_COMMITMENT {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_ORIGINAL_COMMITMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original commitment as varbinary:.
        /// </summary>
        internal static string CAP_ATTR_DETAILS_ORIGINAL_COMMITMENT_VARBINARY {
            get {
                return ResourceManager.GetString("CAP_ATTR_DETAILS_ORIGINAL_COMMITMENT_VARBINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string CAP_ATTRIBUTES {
            get {
                return ResourceManager.GetString("CAP_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        internal static string CAP_AUTH_AUTHENTICATING {
            get {
                return ResourceManager.GetString("CAP_AUTH_AUTHENTICATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate access to personal data.
        /// </summary>
        internal static string CAP_AUTH_INVITE {
            get {
                return ResourceManager.GetString("CAP_AUTH_INVITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting binding key....
        /// </summary>
        internal static string CAP_AUTH_SETTING_BK {
            get {
                return ResourceManager.GetString("CAP_AUTH_SETTING_BK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string CAP_AUTH_TITLE {
            get {
                return ResourceManager.GetString("CAP_AUTH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        internal static string CAP_AUTHENTICATE {
            get {
                return ResourceManager.GetString("CAP_AUTHENTICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        internal static string CAP_AUTHENTICATION_ALERT_TEXT {
            get {
                return ResourceManager.GetString("CAP_AUTHENTICATION_ALERT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failed.
        /// </summary>
        internal static string CAP_AUTHENTICATION_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_AUTHENTICATION_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please authenticate yourself.
        /// </summary>
        internal static string CAP_AUTHENTICATION_INVITATION {
            get {
                return ResourceManager.GetString("CAP_AUTHENTICATION_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometry.
        /// </summary>
        internal static string CAP_BIOMETRY {
            get {
                return ResourceManager.GetString("CAP_BIOMETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance of attributes failed due to error: {0}.
        /// </summary>
        internal static string CAP_BLINKID_ALERT_ATTRIBUTES_ISSUANCE_FAILED {
            get {
                return ResourceManager.GetString("CAP_BLINKID_ALERT_ATTRIBUTES_ISSUANCE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Identity Attributes due to error: {0}.
        /// </summary>
        internal static string CAP_BLINKID_ALERT_ATTRIBUTES_TRANSLATION_FAILED {
            get {
                return ResourceManager.GetString("CAP_BLINKID_ALERT_ATTRIBUTES_TRANSLATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to pass to the Inherence Verifier for regisration due to error: &apos;{0}&apos;.
        /// </summary>
        internal static string CAP_BLINKID_ALERT_SETTING_INHERENCE_FAILED {
            get {
                return ResourceManager.GetString("CAP_BLINKID_ALERT_SETTING_INHERENCE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink ID.
        /// </summary>
        internal static string CAP_BLINKID_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_BLINKID_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan your document for proceeding.
        /// </summary>
        internal static string CAP_BLINKID_INVITATION {
            get {
                return ResourceManager.GetString("CAP_BLINKID_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherence Protection....
        /// </summary>
        internal static string CAP_BTN_INHERENCE_PROTECTION {
            get {
                return ResourceManager.GetString("CAP_BTN_INHERENCE_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change photo.
        /// </summary>
        internal static string CAP_CHANGE_PHOTO {
            get {
                return ResourceManager.GetString("CAP_CHANGE_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string CAP_CONFIRM {
            get {
                return ResourceManager.GetString("CAP_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm request.
        /// </summary>
        internal static string CAP_CONFIRM_REQUEST {
            get {
                return ResourceManager.GetString("CAP_CONFIRM_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Upon clicking on button below you&apos;ll need to take your selfie as requested by the Service Provider.
        /// </summary>
        internal static string CAP_CONFIRM_WITH_PHOTO {
            get {
                return ResourceManager.GetString("CAP_CONFIRM_WITH_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue....
        /// </summary>
        internal static string CAP_CONTINUE_DOTS {
            get {
                return ResourceManager.GetString("CAP_CONTINUE_DOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details....
        /// </summary>
        internal static string CAP_DETAILS {
            get {
                return ResourceManager.GetString("CAP_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        internal static string CAP_DISCLOSE_SECRETS_ALERT_AUTH_FAILURE {
            get {
                return ResourceManager.GetString("CAP_DISCLOSE_SECRETS_ALERT_AUTH_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets were copied to the clipboard. Leave this page?.
        /// </summary>
        internal static string CAP_DISCLOSE_SECRETS_ALERT_COPY_TEXT {
            get {
                return ResourceManager.GetString("CAP_DISCLOSE_SECRETS_ALERT_COPY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclose Secrets.
        /// </summary>
        internal static string CAP_DISCLOSE_SECRETS_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_DISCLOSE_SECRETS_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclose.
        /// </summary>
        internal static string CAP_DISCLOSE_SECRETS_CONFIRM_COMMAND {
            get {
                return ResourceManager.GetString("CAP_DISCLOSE_SECRETS_CONFIRM_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password for disclosing secrets.
        /// </summary>
        internal static string CAP_DISCLOSE_SECRETS_ENTER_PASSWORD {
            get {
                return ResourceManager.GetString("CAP_DISCLOSE_SECRETS_ENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to the Wallet...
        /// </summary>
        internal static string CAP_DISMISS {
            get {
                return ResourceManager.GetString("CAP_DISMISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        internal static string CAP_DOB {
            get {
                return ResourceManager.GetString("CAP_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number:.
        /// </summary>
        internal static string CAP_DOCUMENTNUMBER {
            get {
                return ResourceManager.GetString("CAP_DOCUMENTNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of expiration:.
        /// </summary>
        internal static string CAP_DOE {
            get {
                return ResourceManager.GetString("CAP_DOE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of issue:.
        /// </summary>
        internal static string CAP_DOI {
            get {
                return ResourceManager.GetString("CAP_DOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        internal static string CAP_EMAIL {
            get {
                return ResourceManager.GetString("CAP_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Attribute(s).
        /// </summary>
        internal static string CAP_EMBEDDED_IDPS_TITLE {
            get {
                return ResourceManager.GetString("CAP_EMBEDDED_IDPS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        internal static string CAP_FIRSTNAME {
            get {
                return ResourceManager.GetString("CAP_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to settings....
        /// </summary>
        internal static string CAP_GO_TO_SETTINGS {
            get {
                return ResourceManager.GetString("CAP_GO_TO_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to required permissions....
        /// </summary>
        internal static string CAP_GOTO_REQUIRED_PERMISSIONS {
            get {
                return ResourceManager.GetString("CAP_GOTO_REQUIRED_PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local ID Card:.
        /// </summary>
        internal static string CAP_IDCARD {
            get {
                return ResourceManager.GetString("CAP_IDCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide ID Card content.
        /// </summary>
        internal static string CAP_IDCARD_CONTENT {
            get {
                return ResourceManager.GetString("CAP_IDCARD_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify yourself.
        /// </summary>
        internal static string CAP_IDENTIFY {
            get {
                return ResourceManager.GetString("CAP_IDENTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of {0}.
        /// </summary>
        internal static string CAP_IDENTITY_DET_TITLE {
            get {
                return ResourceManager.GetString("CAP_IDENTITY_DET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of identity.
        /// </summary>
        internal static string CAP_IDENTITY_DET_TITLE2 {
            get {
                return ResourceManager.GetString("CAP_IDENTITY_DET_TITLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization failed.
        /// </summary>
        internal static string CAP_INHERENCE_PROTECTION_ALERT_MSG {
            get {
                return ResourceManager.GetString("CAP_INHERENCE_PROTECTION_ALERT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherence Protection Failed.
        /// </summary>
        internal static string CAP_INHERENCE_PROTECTION_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_INHERENCE_PROTECTION_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherence Protection.
        /// </summary>
        internal static string CAP_INHERENCE_PROTECTION_TITLE {
            get {
                return ResourceManager.GetString("CAP_INHERENCE_PROTECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Root Attribute to use for authentication?.
        /// </summary>
        internal static string CAP_INVITATION_AUTH {
            get {
                return ResourceManager.GetString("CAP_INVITATION_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Root Attribute to use for identification?.
        /// </summary>
        internal static string CAP_INVITATION_IDENTIFY {
            get {
                return ResourceManager.GetString("CAP_INVITATION_IDENTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Root Attribute to use for registration?.
        /// </summary>
        internal static string CAP_INVITATION_REG {
            get {
                return ResourceManager.GetString("CAP_INVITATION_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer:.
        /// </summary>
        internal static string CAP_ISSUER_STATE {
            get {
                return ResourceManager.GetString("CAP_ISSUER_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        internal static string CAP_LASTNAME {
            get {
                return ResourceManager.GetString("CAP_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string CAP_LOGIN {
            get {
                return ResourceManager.GetString("CAP_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        internal static string CAP_LOGIN_ACTION_AUTHENTICATION {
            get {
                return ResourceManager.GetString("CAP_LOGIN_ACTION_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing services....
        /// </summary>
        internal static string CAP_LOGIN_ACTION_INITIALIZING {
            get {
                return ResourceManager.GetString("CAP_LOGIN_ACTION_INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CAP_MAIN_PAGE_ALERT_TITLE_FAILURE {
            get {
                return ResourceManager.GetString("CAP_MAIN_PAGE_ALERT_TITLE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Root Attributes.
        /// </summary>
        internal static string CAP_MY_ATTRIBUTES {
            get {
                return ResourceManager.GetString("CAP_MY_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality:.
        /// </summary>
        internal static string CAP_NATIONALITY {
            get {
                return ResourceManager.GetString("CAP_NATIONALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Alert.
        /// </summary>
        internal static string CAP_NAV_MENU_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_NAV_MENU_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Associated Attributes obtained yet....
        /// </summary>
        internal static string CAP_NO_ASSOCIATED_ATTRIBUTES {
            get {
                return ResourceManager.GetString("CAP_NO_ASSOCIATED_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Root Attributes acquired yet....
        /// </summary>
        internal static string CAP_NO_ROOT_ATTRIBUTES {
            get {
                return ResourceManager.GetString("CAP_NO_ROOT_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data yet....
        /// </summary>
        internal static string CAP_NODATAYET {
            get {
                return ResourceManager.GetString("CAP_NODATAYET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check account existence..
        /// </summary>
        internal static string CAP_O10IDP_ALERT_ACCOUNTCHECK_FAILED {
            get {
                return ResourceManager.GetString("CAP_O10IDP_ALERT_ACCOUNTCHECK_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register with email.
        /// </summary>
        internal static string CAP_O10IDP_ALERT_MAIL_SEND_FAILED {
            get {
                return ResourceManager.GetString("CAP_O10IDP_ALERT_MAIL_SEND_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation mail was sent to: {0}.
        /// </summary>
        internal static string CAP_O10IDP_ALERT_MAIL_SEND_SUCCEEDED {
            get {
                return ResourceManager.GetString("CAP_O10IDP_ALERT_MAIL_SEND_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed due to error &apos;{0}&apos;..
        /// </summary>
        internal static string CAP_O10IDP_ALERT_REGISTRATION_FAILURE {
            get {
                return ResourceManager.GetString("CAP_O10IDP_ALERT_REGISTRATION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending identity attribute failed.
        /// </summary>
        internal static string CAP_O10IDP_ALERT_SENDING_ATTR_FAILED {
            get {
                return ResourceManager.GetString("CAP_O10IDP_ALERT_SENDING_ATTR_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending identity attribute failed due to &apos;{0}&apos;..
        /// </summary>
        internal static string CAP_O10IDP_ALERT_SENDING_ATTR_FAILED_MSG {
            get {
                return ResourceManager.GetString("CAP_O10IDP_ALERT_SENDING_ATTR_FAILED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O10 Identity Provider.
        /// </summary>
        internal static string CAP_O10IDP_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_O10IDP_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating cryptographic commitments....
        /// </summary>
        internal static string CAP_O10IDP_CALCULATING_CRYPTO {
            get {
                return ResourceManager.GetString("CAP_O10IDP_CALCULATING_CRYPTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking account existance....
        /// </summary>
        internal static string CAP_O10IDP_CHECK_REGISTRATION {
            get {
                return ResourceManager.GetString("CAP_O10IDP_CHECK_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your email address.
        /// </summary>
        internal static string CAP_O10IDP_INVITATION {
            get {
                return ResourceManager.GetString("CAP_O10IDP_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a one-time passphrase. An activation email will be sent to the address you specified with link to confirmation page where you&apos;ll be needed to enter provided one-time passphrase..
        /// </summary>
        internal static string CAP_O10IDP_INVITATION2 {
            get {
                return ResourceManager.GetString("CAP_O10IDP_INVITATION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the password of your account.
        /// </summary>
        internal static string CAP_O10IDP_INVITATION3 {
            get {
                return ResourceManager.GetString("CAP_O10IDP_INVITATION3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining issuance details....
        /// </summary>
        internal static string CAP_O10IDP_OBTAIN_DETAILS {
            get {
                return ResourceManager.GetString("CAP_O10IDP_OBTAIN_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting mail sending....
        /// </summary>
        internal static string CAP_O10IDP_REQUEST_MAIL {
            get {
                return ResourceManager.GetString("CAP_O10IDP_REQUEST_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending request for reissuance....
        /// </summary>
        internal static string CAP_O10IDP_REQUEST_REISSUE {
            get {
                return ResourceManager.GetString("CAP_O10IDP_REQUEST_REISSUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O10 Inherence failed due to unexpected error: {0}.
        /// </summary>
        internal static string CAP_O10INHERENCE_ALERT_GENERALFAILURE {
            get {
                return ResourceManager.GetString("CAP_O10INHERENCE_ALERT_GENERALFAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity proofs were invalid.
        /// </summary>
        internal static string CAP_O10INHERENCE_ALERT_IDENTITYPROOFS {
            get {
                return ResourceManager.GetString("CAP_O10INHERENCE_ALERT_IDENTITYPROOFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometric factor registered successfully but registration storing failed..
        /// </summary>
        internal static string CAP_O10INHERENCE_ALERT_REGSTOREFAILED {
            get {
                return ResourceManager.GetString("CAP_O10INHERENCE_ALERT_REGSTOREFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometric factor registered successfully..
        /// </summary>
        internal static string CAP_O10INHERENCE_ALERT_SUCCESS {
            get {
                return ResourceManager.GetString("CAP_O10INHERENCE_ALERT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O10 Inherence.
        /// </summary>
        internal static string CAP_O10INHERENCE_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_O10INHERENCE_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing registration at O10 Inherence failed.
        /// </summary>
        internal static string CAP_O10INHERENCE_ALERT_UNREGISTER_FAILED {
            get {
                return ResourceManager.GetString("CAP_O10INHERENCE_ALERT_UNREGISTER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing registration at O10 Inherence succeeded.
        /// </summary>
        internal static string CAP_O10INHERENCE_ALERT_UNREGISTER_SUCCEEDED {
            get {
                return ResourceManager.GetString("CAP_O10INHERENCE_ALERT_UNREGISTER_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometric verification failed due to error: {0}.
        /// </summary>
        internal static string CAP_O10INHERENCE_ALERT_VERIFICATION_FAILED {
            get {
                return ResourceManager.GetString("CAP_O10INHERENCE_ALERT_VERIFICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to remove your registration at O10 Inherence. Please confirm by entering password and tapping on &apos;Confirm&apos; button..
        /// </summary>
        internal static string CAP_O10INHERENCE_REMOVAL_INVITATION {
            get {
                return ResourceManager.GetString("CAP_O10INHERENCE_REMOVAL_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re going to override your existing secret keys with ones obtained from another device..
        /// </summary>
        internal static string CAP_OVERRIDE_INVITATION {
            get {
                return ResourceManager.GetString("CAP_OVERRIDE_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide password to use for new secret keys.
        /// </summary>
        internal static string CAP_OVERRIDE_PWD_INVITATION {
            get {
                return ResourceManager.GetString("CAP_OVERRIDE_PWD_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onetime passphrase:.
        /// </summary>
        internal static string CAP_PASSPHRASE {
            get {
                return ResourceManager.GetString("CAP_PASSPHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string CAP_PASSWORD {
            get {
                return ResourceManager.GetString("CAP_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a password.
        /// </summary>
        internal static string CAP_PASSWORD_CONTENT {
            get {
                return ResourceManager.GetString("CAP_PASSWORD_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype password.
        /// </summary>
        internal static string CAP_PASSWORD_RETYPE {
            get {
                return ResourceManager.GetString("CAP_PASSWORD_RETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Attribute Value.
        /// </summary>
        internal static string CAP_PROVIDE_ROOT_ATTRIBUTE_VALUE {
            get {
                return ResourceManager.GetString("CAP_PROVIDE_ROOT_ATTRIBUTE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Scanning.
        /// </summary>
        internal static string CAP_QR_SCANNER_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_QR_SCANNER_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string CAP_REGISTER {
            get {
                return ResourceManager.GetString("CAP_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and its confirmation do not match.
        /// </summary>
        internal static string CAP_REGISTER_IDENTITY_ALERT_PASSWORDS_MISMATCH {
            get {
                return ResourceManager.GetString("CAP_REGISTER_IDENTITY_ALERT_PASSWORDS_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Registration.
        /// </summary>
        internal static string CAP_REGISTER_IDENTITY_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_REGISTER_IDENTITY_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string CAP_REGISTER_IDENTITY_CONFIRM_REGISTRATION {
            get {
                return ResourceManager.GetString("CAP_REGISTER_IDENTITY_CONFIRM_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity registration failed due to error &apos;{0}&apos;.
        /// </summary>
        internal static string CAP_REGISTER_IDENTITY_FAILED {
            get {
                return ResourceManager.GetString("CAP_REGISTER_IDENTITY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter one-time passphrase.
        /// </summary>
        internal static string CAP_REGISTER_IDENTITY_PASSPHRASE {
            get {
                return ResourceManager.GetString("CAP_REGISTER_IDENTITY_PASSPHRASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string CAP_REGISTER_IDENTITY_PASSWORD {
            get {
                return ResourceManager.GetString("CAP_REGISTER_IDENTITY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype password.
        /// </summary>
        internal static string CAP_REGISTER_IDENTITY_PASSWORD_CONFIRM {
            get {
                return ResourceManager.GetString("CAP_REGISTER_IDENTITY_PASSWORD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Re)Issue Attribute.
        /// </summary>
        internal static string CAP_REISSUE_ATTR_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_REISSUE_ATTR_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to issue attribute due to error &apos;{0}&apos;.
        /// </summary>
        internal static string CAP_REISSUE_ATTR_FAILED {
            get {
                return ResourceManager.GetString("CAP_REISSUE_ATTR_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request reissue.
        /// </summary>
        internal static string CAP_REQUEST_REISSUE {
            get {
                return ResourceManager.GetString("CAP_REQUEST_REISSUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without photo.
        /// </summary>
        internal static string CAP_REQUEST_ROOT_ATTR {
            get {
                return ResourceManager.GetString("CAP_REQUEST_ROOT_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to the main screen....
        /// </summary>
        internal static string CAP_REQUIRED_PERMISSIONS_NAVIGATING {
            get {
                return ResourceManager.GetString("CAP_REQUIRED_PERMISSIONS_NAVIGATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Attribute Request.
        /// </summary>
        internal static string CAP_ROOT_ATTR_REQ_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_ROOT_ATTR_REQ_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmed one do not match.
        /// </summary>
        internal static string CAP_ROOT_ATTR_REQ_PASSWORD_MISMATCH {
            get {
                return ResourceManager.GetString("CAP_ROOT_ATTR_REQ_PASSWORD_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization failed due to error &apos;{0}&apos;.
        /// </summary>
        internal static string CAP_ROOTATTRDET_ALERT_INIT_FAILED {
            get {
                return ResourceManager.GetString("CAP_ROOTATTRDET_ALERT_INIT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Attribute Details.
        /// </summary>
        internal static string CAP_ROOTATTRDET_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_ROOTATTRDET_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with inherence protection.
        /// </summary>
        internal static string CAP_ROOTATTRDET_WITH_INHERENCE {
            get {
                return ResourceManager.GetString("CAP_ROOTATTRDET_WITH_INHERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to without inherence protection.
        /// </summary>
        internal static string CAP_ROOTATTRDET_WITHOUT_INHERENCE {
            get {
                return ResourceManager.GetString("CAP_ROOTATTRDET_WITHOUT_INHERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan....
        /// </summary>
        internal static string CAP_SCAN {
            get {
                return ResourceManager.GetString("CAP_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR.
        /// </summary>
        internal static string CAP_SCAN_QR {
            get {
                return ResourceManager.GetString("CAP_SCAN_QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select attribute.
        /// </summary>
        internal static string CAP_SELECT_ATTR_INVITATION {
            get {
                return ResourceManager.GetString("CAP_SELECT_ATTR_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick-up provider.
        /// </summary>
        internal static string CAP_SELECT_INHERENCE_PROVIDER {
            get {
                return ResourceManager.GetString("CAP_SELECT_INHERENCE_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        internal static string CAP_SEND_REQUEST {
            get {
                return ResourceManager.GetString("CAP_SEND_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Reset.
        /// </summary>
        internal static string CAP_SETTINGS_ACCOUNT_RESET {
            get {
                return ResourceManager.GetString("CAP_SETTINGS_ACCOUNT_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Hacker Account?.
        /// </summary>
        internal static string CAP_SETTINGS_AUTO_PROTECTION {
            get {
                return ResourceManager.GetString("CAP_SETTINGS_AUTO_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing faces....
        /// </summary>
        internal static string CAP_SP_ACTION_FACES_COMPARISON {
            get {
                return ResourceManager.GetString("CAP_SP_ACTION_FACES_COMPARISON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending request with proofs to the network....
        /// </summary>
        internal static string CAP_SP_ACTION_SENDING_REQUEST {
            get {
                return ResourceManager.GetString("CAP_SP_ACTION_SENDING_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing with the Service Provider....
        /// </summary>
        internal static string CAP_SP_ACTION_SYNC_WITH_SP {
            get {
                return ResourceManager.GetString("CAP_SP_ACTION_SYNC_WITH_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faces comparison failed.
        /// </summary>
        internal static string CAP_SP_ALERT_FACES_COMPARING_FAILURE {
            get {
                return ResourceManager.GetString("CAP_SP_ALERT_FACES_COMPARING_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider.
        /// </summary>
        internal static string CAP_SP_ALERT_TITLE {
            get {
                return ResourceManager.GetString("CAP_SP_ALERT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating binding....
        /// </summary>
        internal static string CAP_SP_CALCULATE_BINDING {
            get {
                return ResourceManager.GetString("CAP_SP_CALCULATE_BINDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to verifiers....
        /// </summary>
        internal static string CAP_SP_GOTO_INHERENCE_VERIFIERS {
            get {
                return ResourceManager.GetString("CAP_SP_GOTO_INHERENCE_VERIFIERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is required verification of your inherence factor but you don&apos;t have registration at any inherence verifier. You can go to inherence verifiers and get registered to any of them..
        /// </summary>
        internal static string CAP_SP_INHERENCE_CHECK_MISSING {
            get {
                return ResourceManager.GetString("CAP_SP_INHERENCE_CHECK_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is required verification of your inherence factor. Please continue with one of following verifiers you&apos;re registered at:.
        /// </summary>
        internal static string CAP_SP_INHERENCE_CHECK_REQUIRED {
            get {
                return ResourceManager.GetString("CAP_SP_INHERENCE_CHECK_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Attribute created basing on this document can be protected with inherence factor using the photo from it. It is highly recommended to add inherence protection. Please toggle switch below for adding inherence factor protection..
        /// </summary>
        internal static string CAP_SUGGEST_INHERENCE_PROTECTION {
            get {
                return ResourceManager.GetString("CAP_SUGGEST_INHERENCE_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take your photo.
        /// </summary>
        internal static string CAP_TAKE_PHOTO {
            get {
                return ResourceManager.GetString("CAP_TAKE_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With photo.
        /// </summary>
        internal static string CAP_TAKE_PHOTO_AND_REQUEST {
            get {
                return ResourceManager.GetString("CAP_TAKE_PHOTO_AND_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister.
        /// </summary>
        internal static string CAP_UNREGISTER {
            get {
                return ResourceManager.GetString("CAP_UNREGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed resolve QR.
        /// </summary>
        internal static string ERR_FAILED_RESOLVE_QR {
            get {
                return ResourceManager.GetString("ERR_FAILED_RESOLVE_QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Auto-Start configured.
        /// </summary>
        internal static string LABEL_CONFIM_AUTO_START {
            get {
                return ResourceManager.GetString("LABEL_CONFIM_AUTO_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; copied to clipboard.
        /// </summary>
        internal static string MSG_COPIED_TO_CP {
            get {
                return ResourceManager.GetString("MSG_COPIED_TO_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Compromised.
        /// </summary>
        internal static string PAGE_TITLE_ACCOUNT_COMPROMISED {
            get {
                return ResourceManager.GetString("PAGE_TITLE_ACCOUNT_COMPROMISED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Creation.
        /// </summary>
        internal static string PAGE_TITLE_ACCOUNT_CREATION {
            get {
                return ResourceManager.GetString("PAGE_TITLE_ACCOUNT_CREATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclose Secrets.
        /// </summary>
        internal static string PAGE_TITLE_DISCLOSE_SECRETS {
            get {
                return ResourceManager.GetString("PAGE_TITLE_DISCLOSE_SECRETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PAGE_TITLE_SETTINS {
            get {
                return ResourceManager.GetString("PAGE_TITLE_SETTINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your Identity to be fully protected, O10 Identity Wallet requires permissions for auto-start and floating window..
        /// </summary>
        internal static string TEXT_ANDROID_PERMISSIONS_INVITATION {
            get {
                return ResourceManager.GetString("TEXT_ANDROID_PERMISSIONS_INVITATION", resourceCulture);
            }
        }
    }
}
