// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Node.DataLayer.Specific.O10Id.DataContexts.SqlServer;

namespace O10.Node.DataLayer.Specific.O10Id.DataContexts.SqlServer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.AccountIdentity", b =>
                {
                    b.Property<long>("AccountIdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("KeyHash")
                        .HasColumnType("decimal(20,0)");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("varbinary(64)");

                    b.HasKey("AccountIdentityId");

                    b.HasIndex("KeyHash");

                    b.ToTable("O10AccountIdentity");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.O10Transaction", b =>
                {
                    b.Property<long>("O10TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("HashKeyO10TransactionHashKeyId")
                        .HasColumnType("bigint");

                    b.Property<long>("Height")
                        .HasColumnType("bigint");

                    b.Property<int>("PacketType")
                        .HasColumnType("int");

                    b.Property<long>("RegistryHeight")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceO10TransactionSourceId")
                        .HasColumnType("bigint");

                    b.HasKey("O10TransactionId");

                    b.HasIndex("HashKeyO10TransactionHashKeyId");

                    b.HasIndex("Height");

                    b.HasIndex("RegistryHeight");

                    b.HasIndex("SourceO10TransactionSourceId");

                    b.ToTable("O10Transactions");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.O10TransactionHashKey", b =>
                {
                    b.Property<long>("O10TransactionHashKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Hash")
                        .HasColumnType("varbinary(64)");

                    b.Property<long>("RegistryHeight")
                        .HasColumnType("bigint");

                    b.HasKey("O10TransactionHashKeyId");

                    b.HasIndex("Hash");

                    b.HasIndex("RegistryHeight");

                    b.ToTable("O10TransactionHashKeys");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.O10TransactionSource", b =>
                {
                    b.Property<long>("O10TransactionSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("IdentityAccountIdentityId")
                        .HasColumnType("bigint");

                    b.HasKey("O10TransactionSourceId");

                    b.HasIndex("IdentityAccountIdentityId");

                    b.ToTable("O10TransactionSources");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.O10Transaction", b =>
                {
                    b.HasOne("O10.Node.DataLayer.Specific.O10Id.Model.O10TransactionHashKey", "HashKey")
                        .WithMany()
                        .HasForeignKey("HashKeyO10TransactionHashKeyId");

                    b.HasOne("O10.Node.DataLayer.Specific.O10Id.Model.O10TransactionSource", "Source")
                        .WithMany("Transactions")
                        .HasForeignKey("SourceO10TransactionSourceId");
                });

            modelBuilder.Entity("O10.Node.DataLayer.Specific.O10Id.Model.O10TransactionSource", b =>
                {
                    b.HasOne("O10.Node.DataLayer.Specific.O10Id.Model.AccountIdentity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityAccountIdentityId");
                });
#pragma warning restore 612, 618
        }
    }
}
