// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using O10.Node.DataLayer.Specific.Registry.DataContexts.SQLite;

namespace O10.Node.DataLayer.Specific.Registry.DataContexts.SQLite
{
    [DbContext(typeof(DataContext))]
    [Migration("20210123032203_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("O10.Node.DataLayer.Specific.Registry.Model.RegistryFullBlock", b =>
                {
                    b.Property<long>("RegistryFullBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .HasColumnType("BLOB");

                    b.Property<string>("Hash")
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("HashString")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SyncBlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionsCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistryFullBlockId");

                    b.HasIndex("SyncBlockHeight");

                    b.ToTable("RegistryFullBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
