name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push Node
      run: |
        docker build . -f dockerfile-node --tag muaddibco/o10node:latest
        docker push muaddibco/o10node:latest
    -
      name: Build and push Gateway
      run: |
        docker build . -f dockerfile-gateway --tag muaddibco/o10gateway:latest
        docker push muaddibco/o10gateway:latest
    -
      name: Build and push Portal
      run: |
        docker build . -f dockerfile-portal --tag muaddibco/o10portal:latest
        docker push muaddibco/o10portal:latest
